### ISSUE TITLE
Discussion about robust Bayesian optimization

### ISSUE THREAD

**Issue by lukasfro** [bayesoptbook/bayesoptbook.github.io#6]
Hi Roman,

First of all, thank you A LOT for making this book publicly available for free. The timing for the publication is absolutely spot on for me as I'm about to finish writing my dissertation on BO and was always looking for a proper textbook as a good reference!

**Description of issue**

The chapter on 'extensions and related settings' already captures quite a lot, however, I was missing the sub-field of robust optimization. 

**Proposed resolution**

The following publications deal with the topic (chronological order):

- https://arxiv.org/pdf/1603.02038.pdf
- https://bayesopt.github.io/papers/2017/15.pdf
- https://proceedings.neurips.cc/paper/2018/file/60243f9b1ac2dba11ff8131c8f4431e0-Paper.pdf
- https://arxiv.org/pdf/2002.02820.pdf
- https://arxiv.org/pdf/2002.09038.pdf

Cheers, Lukas

**Comment by bayesoptbook** [comment]
It's funny you mention this; there has been a comment in the extensions chapter for a months now: `% todo: robust bayesopt??`. Perhaps I should get around to it ;) Thanks for the references!

**Comment by bayesoptbook** [comment]
@rmcantin Can I ask you a couple quick questions about the Garcia-Barcos and Nogueira papers? I'm wondering (1) whether you assume you encounter random perturbations during optimization (rather than performance time) and (2) if so, whether you assume the true perturbation is revealed to you in each iteration? If there's any chance the answers are (1) "yes" and (2) "no," I'm wondering how you deal with inference from noisy inputs with unknown perturbations.

**Comment by bayesoptbook** [comment]
I took at stab at this in the most recent version of the book, rewriting §11.9 to include robust optimization as well. @rmcantin @lukasfro please let me know if you have any feedback on the draft! I'll leave this open for now.

**Comment by lukasfro** [comment]
Looks good from my side besides a small typo in 'Bayesian' for "L. P. Fröhlich et al. (2020). Noisy-Input Entropy Search for Efficient Robust Baeysian Optimization. AISTATS 2020"

**Comment by bayesoptbook** [comment]
oops ;) fixing now
